Editorial: Align with Web IDL specification
w3c/webtransport pull request #226
Opened 2021-03-15 14:54 UTC by autokagami

This is an automated pull request to align the spec with the latest Web IDL specification.

The following is the Web IDL validation message, which may help understanding this PR:

```
Validation error at line 1 in webtransport,4, inside `interface DatagramDuplexStream`:
interface DatagramDuplexStream {
          ^ Interfaces must have `[Exposed]` extended attribute. To fix, add, for example, `[Exposed=Window]`. Please also consider carefully if your interface should also be exposed in a Worker scope. Refer to the [WebIDL spec section on Exposed](https://heycam.github.io/webidl/#Exposed) for more information.
```

Currently this autofix might introduce awkward code formatting, and feel free to manually fix it whenever it happens.

Please file an issue at https://github.com/saschanaz/webidl-updater/issues/new if you think this PR is invalid or should be enhanced.

2021-03-15 15:07 UTC, yutakahirano requested changes

2021-03-15 15:07 UTC, yutakahirano commented on index.bs
> +[Exposed=Window]
[Exposed=(Window,Worker)]

2021-03-16 03:42 UTC, aboba commented on index.bs
> +[Exposed=Window]
Fixed.

2021-03-16 03:43 UTC, aboba approved these changes

2021-03-16 05:18 UTC, yutakahirano commented on index.bs
> +[Exposed=Window]
I think parenthesis are important here.

https://heycam.github.io/webidl/#idl-extended-attributes

2021-03-16 06:46 UTC, yutakahirano approved these changes

2021-03-16 14:54 UTC, merged