Update examples to not await write(bytes)
w3c/webtransport pull request #434
Opened 2022-11-09 21:22 UTC by jan-ivar

Fixes https://github.com/w3c/webtransport/issues/402. Also adds note with a link to the streams spec on this.

2022-11-09 21:29 UTC, wilaw reviewed
Updates look good. While you are refreshing examples, WDYT about adding a new example to show sending a series of data objects as a stream of short lived streams. This mirrors the common use case we are seeing with WARP/RUSH of sending frames or GOPs of video over individual streams.

2022-11-09 23:07 UTC, aboba commented
Have questions about `async function sendData(url, ...data)`

Seems like this async function might be called in a loop where you might want to be able to send multiple messages concurrently, so that `await` usage could be problematic. 

"const writable = await wt.createUnidirectionalStream();"

Can we remove the  `await` here?  Also am concerned with blocking on

  `await writer.close();`

Might substitute `writer.close().catch()`

2022-11-09 23:15 UTC, aboba commented
@willaw I have examples of this in the webcodecs-echo sample.  It took a while to get the message/stream writing functioning well, particularly combined with partial reliability, so might be worth using as an example. 

I also wonder about how to get optimal concurrency on the receiving side, whether `await` usage there is a problem as well.

2022-11-10 00:11 UTC, jan-ivar commented
> After substituting `writer.close().catch()` there was an improvement in concurrency, indicating that `await writer.close()` will block.

Correct. [close()](https://streams.spec.whatwg.org/#ws-prototype) blocks until everything has been _"successfully written and the stream successfully closes, or rejects if an error is encountered during this process"_. — This is necessary to surface any errors from failure to send.

> Have questions about `async function sendData(url, ...data)` ... Seems like this async function might be called in a loop where you might want to be able to send multiple messages concurrently.

If `sendData(url, ...data)` fails to send everything, it rejects. That's its contract, and the promise surfaces that error.

To get concurrency, loop synchronously and gather up promises. There's no back pressure between streams.
```js
await Promise.all(messages.map(arrayOfData => sendData(url, ...arrayOfData)));
```

At least the example now shows how to queue multiple chunks of data efficiently. If we still find it confusing, one option might be to model it closer to the [streams spec's example](https://streams.spec.whatwg.org/#example-manual-write-dont-await), which avoids this problem by never succeeding (`writeSuppliedBytesForever` only rejects on failure).

2022-11-10 00:32 UTC, jan-ivar commented
> I also wonder about how to get optimal concurrency on the receiving side, whether await usage there is a problem as well.

Every `await` is an opportunity to do something else, i.e. the antithesis of concurrency. While `await p; f()` is just syntactic sugar to make `p.then(f)` read like blocking code, apps still need to think through which operations depend on one another (and need to form promise-chains to surface errors correctly) and which don't, and shouldn't. `async` IFFEs with `await` can be used to branch chains.

The streams spec introduces `pipeTo` and `pipeThrough` to guide apps with how to organize this difficult code.

2022-11-21 19:08 UTC, aboba commented
@jan-ivar I have been experimenting with removal of `await` on both the sending and receiving sides.  Replacing `await writer.write()` with `await writer.ready; writer.write()` went smoothly, but replacing `await writer.close()` with `writer.close().then()` has had unexpected side effects, resulting in growing frame RTTs, regardless of the sending rate.  I am wondering if this is the result of leaving too many streams open. 

`writer.close().then()`:  https://webrtc.internaut.com/wc/wtSender7/
`await writer.close()`:   https://webrtc.internaut.com/wc/wtSender8/

2022-11-21 19:11 UTC, aboba requested changes
Line 2159: `await writer.close()`  Is this also a concurrency issue?  I have tried replacing this with `writer.close().then()` in the WebCodecs echo sample, and got some unexpected results.

2022-11-22 15:13 UTC, merged